spring:
  application:
    name: kafka-demo

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      group-id: demo-group
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer